### ISSUE TITLE
留言板 | PyQt5社区

### ISSUE THREAD

**Issue by 892768447** [PyQt5/blog#1]
https://pyqt5.com/guestbook/ 

 Coding Changes the World

**Comment by 892768447** [comment]
沙发

**Comment by bingshilei** [comment]
我是小喷泉，支持老大新的blog.

**Comment by Mr-Second** [comment]
感谢大佬们的教程blog

**Comment by PureBulb** [comment]
感谢大佬的教程

**Comment by zizle** [comment]
github全部Fork了，支持老大出个自定义QLabel控件实现像h5的广告轮播效果

**Comment by ldyivan** [comment]
趴

**Comment by 892768447** [comment]
> github全部Fork了，支持老大出个自定义QLabel控件实现像h5的广告轮播效果

https://github.com/PyQt5/PyQt/blob/master/QPropertyAnimation/PageSwitching.py

**Comment by ldyivan** [comment]
微信小程序是怎么实现的？有Github开源嘛 :)

**Comment by 892768447** [comment]
> 微信小程序是怎么实现的？有Github开源嘛 :)

这个暂时没有开源哦，利用小程序的一些ui模板+ github 的api接口就可以了

**Comment by zizle** [comment]
非常有用，感谢老大.
用PyQt5开发的程序怎么打包成有安装向导的程序呀。我使用Pyinstaller打包，然后用setupfactory总是出现各种错误。要不就是到别的电脑就无法打开什么都不提示。这最后一步始终搞得乱七八糟

在 2019-08-08 23:59:34，"ヽoo悾絔℅o。" <notifications@github.com> 写道：


github全部Fork了，支持老大出个自定义QLabel控件实现像h5的广告轮播效果

https://github.com/PyQt5/PyQt/blob/master/QPropertyAnimation/PageSwitching.py

**Comment by 892768447** [comment]
> 非常有用，感谢老大. 用PyQt5开发的程序怎么打包成有安装向导的程序呀。我使用Pyinstaller打包，然后用setupfactory总是出现各种错误。要不就是到别的电脑就无法打开什么都不提示。这最后一步始终搞得乱七八糟 在 2019-08-08 23:59:34，"ヽoo悾絔℅o。" <notifications@github.com> 写道： github全部Fork了，支持老大出个自定义QLabel控件实现像h5的广告轮播效果 https://github.com/PyQt5/PyQt/blob/master/QPropertyAnimation/PageSwitching.py — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

pyinstaller 打包有各种各样的情况问题，具体结合官网issues和https://github.com/PyQt5/PyQt/issues 和百度上的教程解决

**Comment by zizle** [comment]
感谢大佬的分享开源。不知道能否用PyQt做中国地图，不使用嵌入html的形式，支持出教程

**Comment by zizle** [comment]
> 感谢大佬的分享开源。不知道能否用PyQt做中国地图，不使用嵌入html的形式，支持出教程

因为只看到一个显示世界地图。最近做一些数据可视化就想到能否显示中国地图并在上面描点，鼠标交互。简直不要太棒

**Comment by niuzhenjiang** [comment]
大佬您好，我最近遇到了一个问题，我在ubuntu上面打开我的PYQT程序，出现Qt WebEngine ICU data not found at /home/qt/work/install/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/qt/work/install. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/qt/work/install/translations/qtwebengine_locales. Trying application directory...这种错误，大佬知道这个问题出在哪里吗？该如何解决呢？

**Comment by 892768447** [comment]
> qtwebengine_locales

如果你安装了Qt 去Qt目录里搜索qtwebengine_resources这种东西
找到后复制到你上面报错的路径里/home/qt/work/install/resources

比如windows上
![QQ截图20191016142626](https://user-images.githubusercontent.com/5131669/66893590-ffa2f480-f020-11e9-9ded-ca44ab25229b.png)
![QQ截图20191016142641](https://user-images.githubusercontent.com/5131669/66893591-ffa2f480-f020-11e9-864f-e9418fe48df9.png)

**Comment by niuzhenjiang** [comment]
> @892768447
> > qtwebengine_locales
> 
> 如果你安装了Qt 去Qt目录里搜索qtwebengine_resources这种东西
> 找到后复制到你上面报错的路径里/home/qt/work/install/resources
> 
> 比如windows上
> ![QQ截图20191016142626](https://user-images.githubusercontent.com/5131669/66893590-ffa2f480-f020-11e9-9ded-ca44ab25229b.png)
> ![QQ截图20191016142641](https://user-images.githubusercontent.com/5131669/66893591-ffa2f480-f020-11e9-864f-e9418fe48df9.png)
> 

可是这个我是要给客户使用的，没道理让客户自己再去复制这些文件到自己的机子上...另外Ubuntu上面我打开我的程序里的选择文件窗口或者保存文件窗口，它就会报这个错误..Gtk-Message: 14:29:12.239: GtkDialog mapped without a transient parent. This is discouraged，很气啊，这个原因又是什么呢

**Comment by 892768447** [comment]
@niuzhenjiang  
1、gtk的错误不用管它
2、你要给用户用。你发给用户之前的包里就加进去

**Comment by niuzhenjiang** [comment]
> @892768447
> @niuzhenjiang  
> 1、gtk的错误不用管它
> 2、你要给用户用。你发给用户之前的包里就加进去
> 

我用的是pyside2，并且我发给客户的包里 百分百是包含了这些文件的，但是不知道为什么，终端会按照这个路径去搜索文件，不在我的包里搜索。然后刚才我又试了一遍，关闭程序的时候终端会报：段错误 (核心已转储)，ubuntu好坑爹啊

**Comment by xiaohuihuitop** [comment]
我刚开始使用PyQT5，在我看来，使用QT设计器使用ui文件有两种方法。一种方法是直接使用uic.loadui（）和另一个是使用pyuic5.exe将ui文件转换为py文件。我的问题是哪个更有效？你什么时候会选择一个而不是另一个？在

**Comment by xiaohuihuitop** [comment]
为什么要将.ui文件转化为.py文件呢  直接加载ui文件和调用py文件 有什么差距呢

**Comment by 892768447** [comment]
> 为什么要将.ui文件转化为.py文件呢 直接加载ui文件和调用py文件 有什么差距呢

有多种方式加载UI
1、直接加载UI，这样可以方便动态加载，但是缺点如果UI中的控件名字改变则会导致程序中代码引用变量异常。
2、通过转换为py文件则是解决上面的问题，但缺少了动态加载的优势，不过可以更好的提升编辑器变量智能提示
