### ISSUE TITLE
pyqtclient

### ISSUE THREAD

**Issue by 892768447** [PyQt5/blog#2]
https://pyqt5.com/pyqtclient.html 

 对本博客所写的项目PyQt例子进行一个客户端的编写，客户端主要实现一些动画效果，更换皮肤，运行例子等功能。

**Comment by dream10201** [comment]
拉泡屎，留点东西

**Comment by 892768447** [comment]
## 欢迎测试使用

**Comment by PyQtSite** [comment]
> @892768447
> ## 欢迎测试使用

赞

**Comment by 892768447** [comment]
下载客户端查看更多例子

**Comment by lls-git** [comment]
做的很好啊

**Comment by 892768447** [comment]
> 做的很好啊

谢谢支持

**Comment by lls-git** [comment]
> @892768447
> > 做的很好啊
> 
> 谢谢支持

拿来改着用没问题吧

**Comment by 892768447** [comment]
> @lls-git
> > @892768447
> > > 做的很好啊
> > 
> > 谢谢支持
> 
> 拿来改着用没问题吧

没有的，开源的

**Comment by lls-git** [comment]
请教下里面的图标用的是fontawesome-webfont吗
对应的关系在哪里能查到

**Comment by 892768447** [comment]
> 请教下里面的图标用的是fontawesome-webfont吗
> 对应的关系在哪里能查到

这里我在封装一个。里么有映射
https://github.com/PyQt5/CustomWidgets/tree/master/CustomWidgets/CFontIcon

**Comment by lls-git** [comment]
> @892768447
> > 请教下里面的图标用的是fontawesome-webfont吗
> > 对应的关系在哪里能查到
> 
> 这里我在封装一个。里么有映射
> https://github.com/PyQt5/CustomWidgets/tree/master/CustomWidgets/CFontIcon

谢谢回复
这个很有用

不过我想了解下PyQtClient里面是怎么设置的
是通过qss里面类似这样
#buttonHome {
    qproperty-text: "\5103";
}
实现的吗
这个数字和图标的对应关系怎么确定的

**Comment by 892768447** [comment]
> > @892768447
> > > 请教下里面的图标用的是fontawesome-webfont吗
> > > 对应的关系在哪里能查到
> > 
> > 
> > 这里我在封装一个。里么有映射
> > https://github.com/PyQt5/CustomWidgets/tree/master/CustomWidgets/CFontIcon
> 
> 谢谢回复
> 这个很有用
> 
> 不过我想了解下PyQtClient里面是怎么设置的
> 是通过qss里面类似这样
> #buttonHome {
> qproperty-text: "\5103";
> }
> 实现的吗
> 这个数字和图标的对应关系怎么确定的

映射表里的值，qss里要设置的话一样的。可以用\uf001这样。 f001就是映射表里0x后面的

**Comment by lls-git** [comment]
> @892768447
> > > @892768447
> > > > 请教下里面的图标用的是fontawesome-webfont吗
> > > > 对应的关系在哪里能查到
> > > 
> > > 
> > > 这里我在封装一个。里么有映射
> > > https://github.com/PyQt5/CustomWidgets/tree/master/CustomWidgets/CFontIcon
> > 
> > 谢谢回复
> > 这个很有用
> > 
> > 不过我想了解下PyQtClient里面是怎么设置的
> > 是通过qss里面类似这样
> > #buttonHome {
> > qproperty-text: "\5103";
> > }
> > 实现的吗
> > 这个数字和图标的对应关系怎么确定的
> 
> 映射表里的值，qss里要设置的话一样的。可以用\uf001这样。 f001就是映射表里0x后面的

好的
我试下
非常感谢

**Comment by Dreamsting** [comment]
MAC 上使用不可以吗？ 许多包导入之后都有问题

**Comment by 892768447** [comment]
> MAC 上使用不可以吗？ 许多包导入之后都有问题

参考下博客里有网友发表的一篇文章，搜索mac
