### ISSUE TITLE
cgitb

### ISSUE THREAD

**Issue by 892768447** [PyQt5/blog#3]
https://pyqt5.com/cgitb.html 

 Python PyQt PyQt5 PyQt4 PySide PySide2

**Comment by lovejunjie1** [comment]
想找一个stdout的另一种写法，这个跟我想要的不太一样，要引入新模块

**Comment by 892768447** [comment]
@lovejunjie1  这个引入模块没什么毛病啊。而且本身里面的实现就是和stdout差不多啊。

**Comment by lovejunjie1** [comment]
> @892768447
> @lovejunjie1  这个引入模块没什么毛病啊。而且本身里面的实现就是和stdout差不多啊。

我试试看，如果能用起来的话，就它了
