### ISSUE TITLE
如何查阅Qt文档 | PyQt5

### ISSUE THREAD

**Issue by 892768447** [PyQt5/blog#30]
https://pyqt5.com/viewapi.html 

 很多网友在问有没有PyQt5的文档之类的问题，在PyQt4的时候PyQt官网有了英文版的文档，随后有网友翻译成了中文。不过现在PyQt5官方的文档都指向了C++的Qt文档，其实C++的Qt API文档结构很清晰，翻阅很容易的，需要注意几点。

**Comment by sun2658075** [comment]
文章非常 Nice

**Comment by guiziMountainPerson** [comment]
向博主多多学习

**Comment by children1987** [comment]
感谢分享！
